### ISSUE TITLE
Request for Limited Permissions Scope in Chrome Extension Manifest

### ISSUE THREAD

**Issue by marcelchastain** [Exoceus/cloak#1]
Hello,

I've been using your Chrome extension designed for Google Calendar and find it incredibly useful. However, I've noticed that the extension currently requests overly broad permissions, specifically "Read and change all your data on all websites." 

<img width="497" alt="Screenshot 2023-08-17 at 4 12 05 PM" src="https://github.com/Exoceus/cloak/assets/239227/82451422-41ae-4d5f-9a8f-87ea6a87649e">

Since the extension is primarily intended for enhancing Google Calendar, it might be beneficial to narrow down its permissions to only what is necessary for its intended functionality.

**Issue:**
The current permissions granted to the extension can potentially raise privacy concerns as they allow access to data across all websites. For a Google Calendar extension, these broad permissions seem unnecessary and might discourage users from installing the extension due to the extensive access it requires.

**Suggestion:**
I would like to suggest modifying the extension's permissions to limit its scope to "calendar.google.com" only. This change would help in establishing a sense of trust with users, as they would know that the extension is only accessing data within the intended domain and not across all websites.

**Technical Details:**
To implement this change, you will need to update the `manifest.json` file of the extension with the appropriate permissions. Currently, the permissions might look something like this:

```json
"permissions": [
    "activeTab",
    "storage",
    "webNavigation",
    "webRequest",
    "webRequestBlocking",
    "http://*/*",
    "https://*/*"
]
```

To limit the permissions to "calendar.google.com," you can modify the permissions as follows:

```json
"permissions": [
    "activeTab",
    "storage",
    "webNavigation",
    "webRequest",
    "webRequestBlocking",
    "https://calendar.google.com/*"
]
```

By making this change, the extension will only have access to data on the Google Calendar domain.

I believe that by implementing this change, you can provide users with more confidence in the extension's intentions and encourage wider adoption among those who are concerned about privacy and security.

Thank you for your consideration. I look forward to hearing your thoughts on this suggestion and whether it's feasible to implement.

**Comment by Exoceus** [comment]
Hey, 

Thanks for opening the first issue on this repo! I am glad that the extension is useful. Actually, the reason for this setting is because the extension checks which page you are to display a warning message like this: 
![image](https://github.com/Exoceus/cloak/assets/27310726/b938af61-5958-436e-a613-a343edf78b33)

While it seemed useful at the time, this "feature" is pretty useless. So, Ill be removing it in the upcoming release
