### ISSUE TITLE
Support for Tasks integration?

### ISSUE THREAD

**Issue by irnoham** [Exoceus/cloak#11]
Love this extension!
Now that Google Calendar has Google Tasks integrated it would be nice if Google Tasks were cloaked as well. If you click the tasks button it changes to the task view with a white background but the borders are themed by Cloak.

**Comment by Exoceus** [comment]
Could you attach a screenshot of the button you are clicking?

**Comment by irnoham** [comment]
[image: image.png]
Here's the result:
[image: image.png]
Thanks!
-- 
David Fletcher
(904)719-8086
First Coast IT
To open a support ticket send a message to ***@***.***
Click here to schedule a meeting with me <https://firstcoast.it/cal-df>
Review us on Google! <https://firstcoast.it/review>

**Comment by irnoham** [comment]
Didn't realize pictures wouldn't  come through via email.
Here's the button:
![image](https://github.com/Exoceus/cloak/assets/119874918/5c2e1ef6-b5aa-4a30-9220-945633364a11)

Here's the resulting page:
![image](https://github.com/Exoceus/cloak/assets/119874918/37c6b8b1-4eec-40fe-846b-0b5e7786ff90)

**Comment by Exoceus** [comment]
This extension has been archived :(
