### ISSUE TITLE
Can't Change Text Color

### ISSUE THREAD

**Issue by nattowo** [Exoceus/cloak#13]
Hello! I created an account for this because this is my favorite app for Dark Mode
I just opened my Google Calendar today and found out I can't change the text color through customizations
I think the new update did something, because it was working fine yesterday

**Comment by Exoceus** [comment]
Could you check which version you are on?

I believe this is fixed in v0.3.3

**Comment by nattowo** [comment]
Thank you for replying!
I redownloaded v0.3.3 and the text in Dark Mode is barely visible
![Screenshot 2024-03-24 023254](https://github.com/Exoceus/cloak/assets/164616481/4f2b9fcd-7205-4233-ad4d-b83c6cbdcac9)
The color of the text doesn't change in custom
![image](https://github.com/Exoceus/cloak/assets/164616481/55f47b28-96c2-4ba8-9d7c-f6c58ce049e7)

**Comment by Exoceus** [comment]
I have decided to stop supporting this project as I am just not able/interested in keeping up with the constant updates from GCal breaking this extension.
